name: Coverage
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./site/jacoco-ut/jacoco.xml
