name: Coverage
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Retrieve codecov bash script
        run: curl -s https://codecov.io/bash -o codecov.sh
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./target/site/jacoco-ut/jacoco.xml
